# Generated by Django 5.2.12 on 2026-04-07 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Optional image link for the item', max_length=500, null=True)),
                ('contact_info', models.CharField(help_text="Phone number or location like 'find me in Room 204'", max_length=200)),
                ('last_seen_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('is_resolved', models.BooleanField(default=False, help_text='CR drops this to True once resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
    ]
