# Generated by Django 5.2.12 on 2026-04-07 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=200)),
                ('drive_link', models.URLField(help_text='Must be a valid Google Drive link', max_length=500)),
                ('material_type', models.CharField(choices=[('classroom', 'Google Classroom'), ('pdf', 'Drive PDF'), ('ppt', 'Drive PPT'), ('youtube', 'YouTube'), ('other', 'Other')], default='other', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('thank_you_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialThankYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_yous', to='materials.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_thanks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('material', 'student')},
            },
        ),
    ]
